services:
  nexus:
    container_name: nexus
    image: sonatype/nexus3:3.68.1
    restart: unless-stopped
    volumes:
      - nexus-data:/nexus-data
    ports:
      - 8081:8081
    network_mode: "host"

volumes:
